#ifndef QWEBDOMO_GLOBAL_H
#define QWEBDOMO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QWEBDOMO_LIBRARY)
#  define QWEBDOMOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QWEBDOMOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QWEBDOMO_GLOBAL_H
